# Generated by Django 4.2.11 on 2024-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=200, null=True)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedby', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('stars', models.CharField(max_length=5)),
            ],
        ),
    ]
