# Generated by Django 4.2.11 on 2024-07-17 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered Up to 10 digits allowed.', regex='\\d{10}')]),
        ),
    ]
